version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: graphiti-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - graphiti-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  graphiti-network:
    driver: bridge